name: Unit tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, mbstring, zip, intl, fileinfo
          coverage: none
      - run: composer install --prefer-dist --no-interaction
      - run: vendor/bin/phpstan
      - run: vendor/bin/phpunit ./tests
